name: Deploy to VPS
on:
  push:
    branches: [ main ] # Setiap kali push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 76.13.196.116
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v24.13.1/bin
            cd /root/superkafe
            git fetch --all
            git reset --hard origin/main
            cd frontend
            # Inject Environment Variables
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
            
            npm install
            npm run build
            pm2 restart superkafe-web
            pm2 restart superkafe-server